@token = TU_TOKEN_AQUI
@base = http://localhost:8001

### Login
POST {{base}}/auth/login
Content-Type: application/json

{
    "usuario": "admin",
    "contrasena": "admin123"
}

### Logout
POST {{base}}/auth/logout
Authorization: {{token}}

### Validate
POST {{base}}/auth/validate
Authorization: {{token}}

### Listar usuarios
GET {{base}}/usuarios
Authorization: {{token}}

### Obtener usuario
GET {{base}}/usuarios/1
Authorization: {{token}}

### Crear usuario
POST {{base}}/usuarios
Content-Type: application/json
Authorization: {{token}}

{
    "nombre": "Juan David García",
    "correo": "juandavid@empresa.com",
    "usuario": "juandavid",
    "contrasena": "juan123",
    "rol": "empleado"
}

### Editar usuario
PUT {{base}}/usuarios/1
Content-Type: application/json
Authorization: {{token}}

{
    "nombre": "Juan David García López",
    "rol": "gestion_humana"
}

### Cambiar estado
PATCH {{base}}/usuarios/1/estado
Content-Type: application/json
Authorization: {{token}}

{
    "estado": "inactivo"
}