### Login
POST http://localhost:8001/auth/login
Content-Type: application/json

{
    "usuario": "admin",
    "contrasena": "admin123"
}

### Logout
POST http://localhost:8001/auth/logout
Authorization: TU_TOKEN_AQUI

### validate
POST http://localhost:8001/auth/validate
Authorization: TOKEN_AQUI